# @package _global_
dm:
  _target_: datamodules.cifar10.CIFAR10DataModule
  train_dataset_size: 0.8
  train_dataloader_conf:
    batch_size: 64
    pin_memory: true
    shuffle: true
    num_workers: 4

  val_dataloader_conf:
    batch_size: 64
    pin_memory: true
    num_workers: 4
