# @package _global_
dm:
  _target_: datamodule.cifar100.CIFAR100DataModule
  train_dataloader_conf:
    batch_size: 32
    pin_memory: true
    shuffle: true
    num_workers: 4

  val_dataloader_conf:
    batch_size: 64
    pin_memory: true
    num_workers: 4
