# Name and output dir
name: densenet
checkpoint_dir: ~/checkpoint/densenets

# General configuration
logger: true
ckpt: true
saving_freq: 10

# LightningModule
lm:
  optimizer: SGD
  learning_rate: 0.001
  weight_decay: 0.05
  num_classes: 10

# pl.Trainer configs
pl:
  max_epochs: 10
  gpus: -1
  fast_dev_run: false
  overfit_batches: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
