# .ps_project/config.yaml:

    version: 2

    workflows:
      experiment-workflow:
        steps:
          -
            name: "my-experiment"
            command: experiment.run_single_node
            params:
              command: python -m model.efficientnets.run pl.max_epochs=1 +pl.limit_train_batches=1 +pl.limit_val_batches=1 +pl.limit_test_batches=1
              container: ydcjeff/dl-ci
              experimentEnv:
                EPOCHS_EVAL: 5
                EVAL_SECS: 10
                MAX_STEPS: 1000
                TRAIN_EPOCHS: 10
              machineType: P5000
              modelPath: /artifacts
              modelType: Tensorflow
              name: mnist-cli-config-yaml
            checks: #[optional]
              onnx:loss:
                target: "0.0..0.5"
                aggregate: "mean"
              defaults: #[optional]
                precision: 3
          triggers:
            branches:
              ignore: irrelevant-branch
